[build]
    functions = "./netlify/functions"
    publish = "./"

[[headers]]
  for = "/*.js"
    [headers.values]
      Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "https://frases-para-rivania.netlify.app/:splat"
  status = 301
  force = true
